spring:
  application:
    name: sample-service
  profiles:
    active: dev,prod

server:
  port: 8084  # Specify server port

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
