spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/user/**

        - id: sample-service
          uri: http://localhost:8086
          predicates:
            - Path=/sample/**

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: DEBUG  # Set root level to DEBUG to capture all logs
    org.springframework.cloud.gateway: DEBUG
  console:
    enabled: true  # Ensure console logging is enabled
  file:
    enabled: false  # Disable file-based logging for simplicity in development
