version: '4'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-order-service
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3308:3306"
    volumes:
      - /Users/amieldelosreyes/Desktop/Amiel Microservices/amiel-microservice-ecosystem/order-service/mysql:/var/lib/mysql
      - /Users/amieldelosreyes/Desktop/Amiel Microservices/amiel-microservice-ecosystem/order-service/docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql