spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3308/order-service
    username: root
    password: mysql

  jpa:
    hibernate:
      ddl-auto: none
    flyway:
      enabled: true

server:
  port: 8081

