spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://localhost:8181/realms/miel-microservices-security-realm'
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**

        - id: sample-service
          uri: lb://sample-service
          predicates:
            - Path=/sample/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
            
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**    

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    path: '/api-docs'
  swagger-ui:
    path: '/swagger-ui.html'
    urls:
      - name: Product Service
        url: /aggregate/product-service/v3/api-docs

      - name: Order Service
        url: /aggregate/order-service/v3/api-docs

      - name: Inventory Service
        url: /aggregate/inventory-service/v3/api-docs

      - name: Sample Service
        url: /aggregate/sample-service/v3/api-docs

      - name: User Service
        url: /aggregate/user-service/v3/api-docs
