spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:mysql://localhost:3307/inventory-service
    username: root
    password: mysql

  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8082

springdoc:
  api-docs:
    path: '/v3/api-docs'
  swagger-ui:
    path: '/swagger-ui.html'
