spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3308/order-service
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8081

springdoc:
  api-docs:
    path: '/v3/api-docs'
  swagger-ui:
    path: '/swagger-ui.html'
