spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3308/order-service
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8081

springdoc:
  api-docs:
    path: '/api-docs'
  swagger-ui:
    path: '/swagger-ui.html'

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "circuitbreakers, health, info"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
      show-details: always
    circuitbreakers:
      enabled: true
      show-details: always


resilience4j:
  circuitbreaker:
    configs:
      inventory:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimumNumberOfCalls: 5
  timelimiter:
    configs:
      inventory:
        timeout-duration: 3s
  retry:
    configs:
      inventory:
        max-attempts: 3
        wait-duration: 2s

fallback:
  path: /fallbackRoute
  response:
    status: 503
    body: "Service Unavailable, please try again later."
