spring:
  application:
    name: product-service

  data:
    data:
      mongodb:
        uri: mongodb://root:password@localhost:27017/?authSource=admin
        host: localhost
        port: 27017
        username: root
        password: password
        database: product-service

server:
  port: 8084

springdoc:
  api-docs:
    path: '/api-docs'
  swagger-ui:
    path: '/swagger-ui.html'
