spring:
  application:
      name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        
server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

opentracing:
  jaeger:
    enabled: true
    udp-sender:
      host: localhost
      port: 6831

springdoc:
  api-docs:
    path: '/api-docs'
  swagger-ui:
    path: '/swagger-ui.html'