spring:
  application:
    name: product-service

  data:
    data:
      mongodb:
        uri: mongodb://root:password@localhost:27017/?authSource=admin
        host: localhost
        port: 27017
        username: root
        password: password
        database: product-service