spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/amieldelosreyes/Desktop/Amiel%20Microservices/amiel-microservice-ecosystem/config
#        git: for remote git config server
#          url:
#          username:
#          password:

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8888

