version: '4'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-inventory-service
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3307:3306"
    volumes:
      - /Users/amieldelosreyes/Desktop/Amiel Microservices/amiel-microservice-ecosystem/inventory-service/mysql:/var/lib/mysql
      - /Users/amieldelosreyes/Desktop/Amiel Microservices/amiel-microservice-ecosystem/inventory-service/docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql